#!/usr/bin/env node
/**
 * fetch-inbeta.mjs — generate a page for every In Beta episode from
 * inbetaphysio.com, and rebuild the In Beta section of the Podcasts index.
 *
 * In Beta keeps the audio. Each page here carries the metadata and a short
 * summary and then sends the reader to the original post to listen. Nothing is
 * rehosted and no player is embedded, so the show's own pages and download
 * counts stay the only route to the recordings.
 *
 * Existing episode pages are never overwritten — tags, `related:` links and any
 * hand-written additions survive every run. Pass --force to rewrite them.
 *
 * Source: the WordPress REST API. The podcast RSS feed is not usable — it caps
 * at 10 items and silently ignores `?paged=`, returning the same 10 every time.
 * The REST API returns all 42 in one call and carries the running time in
 * `meta.duration`, which the feed does not.
 *
 *   node scripts/fetch-inbeta.mjs             # create missing pages, rebuild index
 *   node scripts/fetch-inbeta.mjs --dry-run   # report what would happen
 *   node scripts/fetch-inbeta.mjs --force     # also rewrite existing pages
 */

import { readFile, writeFile, readdir } from "node:fs/promises"
import { existsSync } from "node:fs"
import path from "node:path"

const SITE = "https://inbetaphysio.com"
const CATEGORY_SLUG = "podcasts"
const DIR = "content/Podcasts"
const INDEX = `${DIR}/index.md`
const START = "<!-- inbeta:start — generated by scripts/fetch-inbeta.mjs; do not edit by hand -->"

// Posts in the Podcasts category that are not In Beta episodes. The
// Environmental Healthcare Unconference set was Ben Ellis's own project, hosted
// on In Beta; Michael had no part in it, so it does not belong on his site.
const EXCLUDED_SLUGS = new Set([
  "environmental-healthcare-unconference-podcast-1",
  "environmental-healthcare-unconference-podcast-2",
  "environmental-healthcare-unconference-podcast-3",
  "environmental-healthcare-unconference-podcast-4",
])
const END = "<!-- inbeta:end -->"

const dryRun = process.argv.includes("--dry-run")
const force = process.argv.includes("--force")

const ENTITIES = {
  amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ",
  "#8211": "–", "#8212": "—", "#8216": "‘", "#8217": "’",
  "#8220": "“", "#8221": "”", "#8230": "…", "#038": "&", "#039": "'",
}
const decode = (s = "") =>
  s.replace(/&(#?\w+);/g, (m, e) =>
    ENTITIES[e] ?? (e.startsWith("#") ? String.fromCharCode(Number(e.slice(1))) : m))
const text = (s = "") => decode(s.replace(/<[^>]*>/g, "")).replace(/\s+/g, " ").trim()

// WordPress appends a read-more link to every excerpt:
//   <div class="more-link-wrapper"><a class="more-link">Continue reading<span
//   class="screen-reader-text">#38 – …</span></a></div>
// Stripping tags alone leaves "Continue reading#38 – …" glued to the summary.
const excerpt = (html = "") => text(html.replace(/<div class="more-link-wrapper">[\s\S]*$/i, ""))
const yaml = (s = "") => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`

const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"]

/** Trim to a whole sentence under `max`, falling back to a word boundary. */
function clip(s, max) {
  if (s.length <= max) return s
  const cut = s.slice(0, max)
  const stop = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("? "), cut.lastIndexOf("! "))
  if (stop > max * 0.5) return cut.slice(0, stop + 1)
  return cut.replace(/\s\S*$/, "") + "…"
}

async function json(url) {
  const res = await fetch(url, { headers: { "user-agent": "home-michael/fetch-inbeta" } })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return { body: await res.json(), headers: res.headers }
}

function episodePage(e) {
  const fm = [
    "---",
    "type: podcast",
    `title: ${yaml(e.title)}`,
    `description: ${yaml(e.description)}`,
    `meta-description: ${yaml(e.metaDescription)}`,
    "author:",
    '  - "[[Michael Rowe]]"',
    `date: ${e.iso}`,
    "recorded:",
    "show: In Beta",
    `show-url: ${SITE}/category/podcasts/`,
    "host: Michael Rowe",
    `episode: ${yaml(e.number ?? "")}`,
    "role: host",
    "video:",
    "embed:",
    "audio:",
    `duration: ${yaml(e.duration)}`,
    "tags: []",
    "category: []",
    "related: []",
    "draft: false",
    "linkedin:",
    "---",
    "",
  ]
  const meta = ["**In Beta**", `${e.day} ${e.month} ${e.year}`, e.duration]
    .filter(Boolean)
    .join(" · ")
  return [
    ...fm,
    meta,
    "",
    e.summary,
    "",
    `[Listen to this episode on In Beta →](${e.link})`,
    "",
  ].join("\n")
}

async function main() {
  const { body: cats } = await json(`${SITE}/wp-json/wp/v2/categories?slug=${CATEGORY_SLUG}`)
  const cat = cats[0]
  if (!cat) throw new Error(`no category with slug "${CATEGORY_SLUG}"`)

  const posts = []
  for (let page = 1; ; page++) {
    const { body, headers } = await json(
      `${SITE}/wp-json/wp/v2/posts?categories=${cat.id}&per_page=100&page=${page}&orderby=date&order=desc`)
    posts.push(...body)
    if (page >= Number(headers.get("x-wp-totalpages") ?? 1)) break
  }
  if (posts.length !== cat.count) {
    console.warn(`warning: category reports ${cat.count} posts, fetched ${posts.length}`)
  }

  const excluded = posts.filter((p) => EXCLUDED_SLUGS.has(p.slug))
  if (excluded.length !== EXCLUDED_SLUGS.size) {
    console.warn(`warning: expected ${EXCLUDED_SLUGS.size} excluded posts, matched ${excluded.length} — ` +
      `check EXCLUDED_SLUGS against the source`)
  }

  const episodes = posts.filter((p) => !EXCLUDED_SLUGS.has(p.slug)).map((p) => {
    const d = new Date(p.date)
    const raw = text(p.title?.rendered)
    // Titles are "#36 – Generative AI personas…" or "#4: Guided choice-based
    // learning" — the run used an en dash for 17 episodes and a colon for 21.
    // The number belongs in the `episode` field, not in the page title. Four
    // posts (the Environmental Healthcare Unconference set) carry no number in
    // that position and keep their title whole.
    const m = raw.match(/^#\s*(\d+)\s*[–—:-]\s*(.*)$/)
    const summary = excerpt(p.excerpt?.rendered)
    return {
      iso: p.date.slice(0, 10),
      year: d.getFullYear(),
      month: MONTHS[d.getMonth()],
      day: d.getDate(),
      // The run used "#38 – Title" for 17 episodes and "#4: Title" for 21.
      // Neither convention survives: the catalogue is organised by topic and
      // title, so the number is kept in the `episode` field for the record and
      // appears nowhere on the page.
      number: m ? m[1] : null,
      title: m ? m[2] : raw,
      link: p.link,
      duration: (p.meta?.duration ?? "").trim(),
      summary,
      description: clip(summary, 600),
      metaDescription: clip(summary, 150).replace(/…$/, "…"),
      file: `${p.date.slice(0, 10)}-in-beta-${p.slug}.md`,
    }
  })

  let created = 0, skipped = 0, rewritten = 0
  for (const e of episodes) {
    const file = path.join(DIR, e.file)
    const exists = existsSync(file)
    if (exists && !force) { skipped++; continue }
    if (!dryRun) await writeFile(file, episodePage(e))
    exists ? rewritten++ : created++
  }

  // Index section: a year-by-year list of internal links, like Presentations.
  const years = [...new Set(episodes.map((e) => e.year))].sort((a, b) => b - a)
  const lines = [START, ""]
  for (const year of years) {
    lines.push(`### ${year}`, "")
    for (const e of episodes.filter((x) => x.year === year)) {
      const slug = e.file.replace(/\.md$/, "")
      // The episode number stays OUT of the wikilink alias. Quartz's wikilink
      // regex (quartz/plugins/transformers/ofm.ts) excludes `#` from the alias
      // group, because `#` is the heading separator — an alias containing one
      // silently fails to match and the raw [[…]] is published.
      lines.push(
        `- **${e.day} ${e.month}** · [[Podcasts/${slug}|${e.title}]]${e.duration ? ` *(${e.duration})*` : ""}`)
    }
    lines.push("")
  }
  lines.push(END)
  const section = lines.join("\n")

  if (dryRun) {
    console.log(section)
    console.error(`\n(dry run — ${episodes.length} episodes; would create ${created}, ` +
      `${force ? `rewrite ${rewritten}` : `skip ${skipped} existing`})`)
    return
  }

  const index = await readFile(INDEX, "utf8")
  const from = index.indexOf(START), to = index.indexOf(END)
  if (from === -1 || to === -1) throw new Error(`markers not found in ${INDEX}`)
  await writeFile(INDEX, index.slice(0, from) + section + index.slice(to + END.length))

  // Anything in the folder that no episode claims — a page for a post that has
  // since been deleted or re-slugged — is reported, never removed.
  const known = new Set([...episodes.map((e) => e.file), "index.md"])
  const orphans = (await readdir(DIR))
    .filter((f) => f.endsWith(".md") && f.includes("-in-beta-") && !known.has(f))
  if (orphans.length) console.warn(`orphaned In Beta pages (not removed): ${orphans.join(", ")}`)

  console.log(`${episodes.length} episodes (${years.at(-1)}–${years[0]}): ` +
    `${created} created, ${rewritten} rewritten, ${skipped} left alone. Index rebuilt.`)
}

main().catch((err) => {
  // Non-destructive: a failed fetch leaves the existing pages and index intact.
  console.error(`fetch-inbeta: ${err.message}`)
  console.error("No pages or index changes were written.")
  process.exit(1)
})
